Transfer a file to your server

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,8 +1,21 @@
 #!/usr/bin/env bash
-# Bash script supposed to transfer a file from our client to a server
-if [ "$#" -eq 4 ];
-then
-    scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~/"
+# Bash script to transfer a file from our client to a server
+# Checking for command line arguments
+
+if [ $# -lt 4 ]; then
+    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    exit 1
+fi
+
+# Assigning parameters to variables
+path_to_file=$1
+ip=$2
+username=$3
+path_to_ssh_key=$4
+
+# Disabling strict host key checking and transferring the file
+if scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"; then
+    echo "FILE WAS TRANSFERRED SUCCESSFULLY"
 else
-    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    echo "FILE TRANSFER FAILED"
 fi
